CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" character varying(255) NOT NULL,
    "Role" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "Team" (
    "TeamId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Location" character varying(255) NOT NULL,
    "CoachId" integer NOT NULL,
    "IsPublic" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Team" PRIMARY KEY ("TeamId"),
    CONSTRAINT "FK_Team_Users_CoachId" FOREIGN KEY ("CoachId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Coach" (
    "CoachId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TeamId" integer,
    "ExperienceYears" integer NOT NULL,
    "Specialty" character varying(100) NOT NULL,
    "Certification" character varying(100) NOT NULL,
    "Bio" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Coach" PRIMARY KEY ("CoachId"),
    CONSTRAINT "FK_Coach_Team_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Team" ("TeamId"),
    CONSTRAINT "FK_Coach_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Game" (
    "GameId" integer GENERATED BY DEFAULT AS IDENTITY,
    "HomeTeamId" integer NOT NULL,
    "AwayTeamId" integer NOT NULL,
    "GameDate" timestamp with time zone NOT NULL,
    "Location" character varying(255) NOT NULL,
    "HomeScore" integer NOT NULL,
    "AwayScore" integer NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Season" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Game" PRIMARY KEY ("GameId"),
    CONSTRAINT "FK_Game_Team_AwayTeamId" FOREIGN KEY ("AwayTeamId") REFERENCES "Team" ("TeamId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Game_Team_HomeTeamId" FOREIGN KEY ("HomeTeamId") REFERENCES "Team" ("TeamId") ON DELETE CASCADE
);

CREATE TABLE "Player" (
    "PlayerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TeamId" integer NOT NULL,
    "Position" character varying(50) NOT NULL,
    "Age" integer,
    "Height" character varying(10) NOT NULL,
    "Weight" integer,
    "JerseyNumber" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Player" PRIMARY KEY ("PlayerId"),
    CONSTRAINT "FK_Player_Team_TeamId" FOREIGN KEY ("TeamId") REFERENCES "Team" ("TeamId") ON DELETE CASCADE,
    CONSTRAINT "FK_Player_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "GameNote" (
    "GameNoteId" integer GENERATED BY DEFAULT AS IDENTITY,
    "GameId" integer NOT NULL,
    "CoachId" integer NOT NULL,
    "NoteType" character varying(20) NOT NULL,
    "Content" text NOT NULL,
    "Title" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GameNote" PRIMARY KEY ("GameNoteId"),
    CONSTRAINT "FK_GameNote_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE,
    CONSTRAINT "FK_GameNote_Users_CoachId" FOREIGN KEY ("CoachId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "PlayerGameStats" (
    "PlayerGameStatsId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerId" integer NOT NULL,
    "GameId" integer NOT NULL,
    "PassingYards" integer NOT NULL,
    "PassingTouchdowns" integer NOT NULL,
    "Interceptions" integer NOT NULL,
    "RushingYards" integer NOT NULL,
    "RushingTouchdowns" integer NOT NULL,
    "ReceivingYards" integer NOT NULL,
    "ReceivingTouchdowns" integer NOT NULL,
    "Receptions" integer NOT NULL,
    "Tackles" integer NOT NULL,
    "Assists" integer NOT NULL,
    "Sacks" integer NOT NULL,
    "ForcedFumbles" integer NOT NULL,
    "InterceptionsDef" integer NOT NULL,
    "FieldGoalsMade" integer NOT NULL,
    "FieldGoalsAttempted" integer NOT NULL,
    "ExtraPointsMade" integer NOT NULL,
    "ExtraPointsAttempted" integer NOT NULL,
    "MinutesPlayed" integer NOT NULL,
    "RecordedBy" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlayerGameStats" PRIMARY KEY ("PlayerGameStatsId"),
    CONSTRAINT "FK_PlayerGameStats_Game_GameId" FOREIGN KEY ("GameId") REFERENCES "Game" ("GameId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerGameStats_Player_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerGameStats_Users_RecordedBy" FOREIGN KEY ("RecordedBy") REFERENCES "Users" ("UserId") ON DELETE SET NULL
);

CREATE TABLE "PlayerGoal" (
    "PlayerGoalId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerId" integer NOT NULL,
    "GoalType" character varying(50) NOT NULL,
    "TargetValue" integer NOT NULL,
    "CurrentValue" integer NOT NULL,
    "Season" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlayerGoal" PRIMARY KEY ("PlayerGoalId"),
    CONSTRAINT "FK_PlayerGoal_Player_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE
);

CREATE TABLE "PlayerNote" (
    "PlayerNoteId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerId" integer NOT NULL,
    "CoachId" integer NOT NULL,
    "Content" text NOT NULL,
    "IsPrivate" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlayerNote" PRIMARY KEY ("PlayerNoteId"),
    CONSTRAINT "FK_PlayerNote_Player_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Player" ("PlayerId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerNote_Users_CoachId" FOREIGN KEY ("CoachId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE INDEX idx_coach_team ON "Coach" ("TeamId");

CREATE UNIQUE INDEX idx_coach_user ON "Coach" ("UserId");

CREATE INDEX idx_away_team ON "Game" ("AwayTeamId");

CREATE INDEX idx_game_date ON "Game" ("GameDate");

CREATE INDEX idx_home_team ON "Game" ("HomeTeamId");

CREATE INDEX idx_gamenote_coach ON "GameNote" ("CoachId");

CREATE INDEX idx_gamenote_game ON "GameNote" ("GameId");

CREATE INDEX idx_player_team ON "Player" ("TeamId");

CREATE INDEX idx_player_user ON "Player" ("UserId");

CREATE UNIQUE INDEX idx_player_game_unique ON "PlayerGameStats" ("PlayerId", "GameId");

CREATE INDEX idx_stats_game ON "PlayerGameStats" ("GameId");

CREATE INDEX idx_stats_player ON "PlayerGameStats" ("PlayerId");

CREATE INDEX "IX_PlayerGameStats_RecordedBy" ON "PlayerGameStats" ("RecordedBy");

CREATE INDEX idx_goal_player ON "PlayerGoal" ("PlayerId");

CREATE INDEX idx_playernote_coach ON "PlayerNote" ("CoachId");

CREATE INDEX idx_playernote_player ON "PlayerNote" ("PlayerId");

CREATE INDEX idx_team_coach ON "Team" ("CoachId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251012201313_InitialCreate', '8.0.4');

COMMIT;

